In [2]:
import numpy as np

In [ ]:
u = np.arange(16).reshape(4,4) #0~15までの数の4*4の行列
u


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.roll(u, 1, axis = 0) #下からはみ出たものが上にくるのか

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.roll(u, -1, axis = 0) #上にはみ出たものが下にくる

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [ ]:
np.roll(u, 1, axis = 1) #上記と異なる回転軸で(右に一つの回転)

array([[ 3,  0,  1,  2],
       [ 7,  4,  5,  6],
       [11,  8,  9, 10],
       [15, 12, 13, 14]])

In [8]:
np.roll(u, -1, axis = 1)

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  4],
       [ 9, 10, 11,  8],
       [13, 14, 15, 12]])